language: node_js
node_js:
  - "statble"
sudo: required
services:
  - docker

  before_install:
    - docker  build -t  vijayforindia/docker-react -f  Dockerfile.dev .

    script:
      - docker run vijayforindia/docker-react npm run test  --  --coverage