language: node_js 
node_js:
- "stable"
sudo: required
services:
  - docker

before_install:
- docker build -t vijayforindia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vijayforindia/docker-react npm run test